import * as fs from 'fs';
import * as path from 'path';
import { TestRunResult, TestCaseResult, EvaluationResult } from '../core/suite';
import { logger } from '../utils/logger';

export class HtmlReporter {
  private outputPath: string;

  constructor(outputPath?: string) {
    this.outputPath = outputPath || './llm-test-results/report.html';
  }

  report(result: TestRunResult): void {
    const dir = path.dirname(this.outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const html = this.generateHtml(result);
    fs.writeFileSync(this.outputPath, html, 'utf-8');
    logger.info(`HTML report saved to ${this.outputPath}`);
  }

  private generateHtml(result: TestRunResult): string {
    const { summary } = result;
    const passRateClass = summary.passRate >= 0.8 ? 'pass' : summary.passRate >= 0.5 ? 'warn' : 'fail';

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>LLM Test Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0d1117; color: #c9d1d9; padding: 24px; }
  .container { max-width: 1000px; margin: 0 auto; }
  h1 { color: #f0f6fc; margin-bottom: 8px; font-size: 24px; }
  .meta { color: #8b949e; font-size: 14px; margin-bottom: 24px; }
  .summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 12px; margin-bottom: 32px; }
  .stat { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 16px; text-align: center; }
  .stat-value { font-size: 28px; font-weight: 700; }
  .stat-label { color: #8b949e; font-size: 12px; text-transform: uppercase; margin-top: 4px; }
  .pass { color: #3fb950; }
  .fail { color: #f85149; }
  .warn { color: #d29922; }
  .suite { margin-bottom: 24px; }
  .suite-header { background: #161b22; border: 1px solid #30363d; border-radius: 8px 8px 0 0; padding: 12px 16px; font-weight: 600; }
  .test { border: 1px solid #30363d; border-top: none; padding: 12px 16px; background: #0d1117; }
  .test:last-child { border-radius: 0 0 8px 8px; }
  .test-header { display: flex; align-items: center; gap: 8px; cursor: pointer; }
  .test-header:hover { opacity: 0.8; }
  .test-icon { font-size: 16px; }
  .test-name { font-weight: 500; flex: 1; }
  .test-meta { color: #8b949e; font-size: 12px; }
  .test-details { display: none; margin-top: 12px; padding: 12px; background: #161b22; border-radius: 6px; font-size: 13px; }
  .test-details.open { display: block; }
  .eval-row { padding: 6px 0; border-bottom: 1px solid #21262d; display: flex; align-items: center; gap: 8px; }
  .eval-row:last-child { border-bottom: none; }
  .eval-type { color: #8b949e; min-width: 100px; font-size: 12px; text-transform: uppercase; }
  .eval-score { font-weight: 600; min-width: 50px; }
  .eval-details { color: #8b949e; font-size: 12px; flex: 1; }
  .prompt-response { margin-top: 8px; }
  .prompt-response label { display: block; color: #8b949e; font-size: 11px; text-transform: uppercase; margin-bottom: 4px; margin-top: 8px; }
  .prompt-response pre { background: #0d1117; border: 1px solid #30363d; border-radius: 4px; padding: 8px; font-size: 12px; white-space: pre-wrap; word-break: break-word; max-height: 200px; overflow-y: auto; }
  .error-msg { color: #f85149; font-size: 13px; margin-top: 4px; }
  .footer { text-align: center; color: #484f58; font-size: 12px; margin-top: 32px; padding-top: 16px; border-top: 1px solid #21262d; }
</style>
</head>
<body>
<div class="container">
  <h1>LLM Test Report</h1>
  <div class="meta">
    ${result.timestamp} &middot; Duration: ${(result.duration / 1000).toFixed(1)}s
  </div>

  <div class="summary">
    <div class="stat">
      <div class="stat-value">${summary.total}</div>
      <div class="stat-label">Total Tests</div>
    </div>
    <div class="stat">
      <div class="stat-value pass">${summary.passed}</div>
      <div class="stat-label">Passed</div>
    </div>
    <div class="stat">
      <div class="stat-value fail">${summary.failed}</div>
      <div class="stat-label">Failed</div>
    </div>
    <div class="stat">
      <div class="stat-value ${passRateClass}">${(summary.passRate * 100).toFixed(1)}%</div>
      <div class="stat-label">Pass Rate</div>
    </div>
    <div class="stat">
      <div class="stat-value">${summary.avgLatencyMs}ms</div>
      <div class="stat-label">Avg Latency</div>
    </div>
    <div class="stat">
      <div class="stat-value">${summary.totalTokens.input + summary.totalTokens.output}</div>
      <div class="stat-label">Total Tokens</div>
    </div>
  </div>

  ${result.suites.map((suite) => this.renderSuite(suite)).join('\n')}

  <div class="footer">
    Generated by llm-testing-toolkit
  </div>
</div>
<script>
document.querySelectorAll('.test-header').forEach(el => {
  el.addEventListener('click', () => {
    const details = el.nextElementSibling;
    if (details) details.classList.toggle('open');
  });
});
</script>
</body>
</html>`;
  }

  private renderSuite(suite: { name: string; tests: TestCaseResult[] }): string {
    return `
  <div class="suite">
    <div class="suite-header">${this.escapeHtml(suite.name)}</div>
    ${suite.tests.map((test) => this.renderTest(test)).join('\n')}
  </div>`;
  }

  private renderTest(test: TestCaseResult): string {
    const icon = test.error ? '!' : test.passed ? '\u2713' : '\u2717';
    const iconClass = test.error ? 'warn' : test.passed ? 'pass' : 'fail';

    return `
    <div class="test">
      <div class="test-header">
        <span class="test-icon ${iconClass}">${icon}</span>
        <span class="test-name">${this.escapeHtml(test.testName)}</span>
        <span class="test-meta">${test.latencyMs}ms</span>
      </div>
      <div class="test-details">
        ${test.error ? `<div class="error-msg">${this.escapeHtml(test.error)}</div>` : ''}
        ${test.evaluations.map((e) => this.renderEvaluation(e)).join('\n')}
        <div class="prompt-response">
          <label>Prompt</label>
          <pre>${this.escapeHtml(test.prompt)}</pre>
          <label>Response</label>
          <pre>${this.escapeHtml(test.response || '(no response)')}</pre>
        </div>
      </div>
    </div>`;
  }

  private renderEvaluation(evaluation: EvaluationResult): string {
    const scoreClass = evaluation.passed ? 'pass' : 'fail';
    return `
        <div class="eval-row">
          <span class="eval-type">${evaluation.evaluator}</span>
          <span class="eval-score ${scoreClass}">${(evaluation.score * 100).toFixed(0)}%</span>
          <span class="eval-details">${this.escapeHtml(evaluation.details)}</span>
        </div>`;
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
}
